CREATE TABLE IF NOT EXISTS media (
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    name TEXT NOT NULL,
    type TEXT NOT NULL,
    duration INTEGER NOT NULL,
    is_deleted INTEGER NOT NULL DEFAULT 0
);
